export const moviesList = [
    {
      id: 1,
      title: "Inception",
      actors: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
      director: "Christopher Nolan",
      country: "USA",
      releaseYear: 2010,
      genre: ["Action", "Sci-Fi"],
      category: "NewThisWeek",
      rating: 8.8,
      duration: "148 min",
      description: "A skilled thief is given a chance at redemption if he can successfully perform inception by planting an idea into the mind of a C.E.O.",
      poster: "https://example.com/inception.jpg"
    },
    {
      id: 2,
      title: "Parasite",
      actors: ["Kang-ho Song", "Sun-kyun Lee", "Yeo-jeong Cho"],
      director: "Bong Joon Ho",
      country: "South Korea",
      releaseYear: 2019,
      genre: ["Thriller", "Drama"],
      category: "TrendingNow",
      rating: 8.6,
      duration: "132 min",
      description: "Greed and class discrimination threaten the relationship between the wealthy Park family and the destitute Kim clan.",
      poster: "https://example.com/parasite.jpg"
    },
    {
      id: 3,
      title: "Interstellar",
      actors: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
      director: "Christopher Nolan",
      country: "USA",
      releaseYear: 2014,
      genre: ["Adventure", "Drama", "Sci-Fi"],
      category: "Epic",
      rating: 8.6,
      duration: "169 min",
      description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
      poster: "https://example.com/interstellar.jpg"
    },
    {
      id: 4,
      title: "The Godfather",
      actors: ["Marlon Brando", "Al Pacino", "James Caan"],
      director: "Francis Ford Coppola",
      country: "USA",
      releaseYear: 1972,
      genre: ["Crime", "Drama"],
      category: "Classic",
      rating: 9.2,
      duration: "175 min",
      description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
      poster: "https://example.com/godfather.jpg"
    },
    {
      id: 5,
      title: "The Dark Knight",
      actors: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
      director: "Christopher Nolan",
      country: "USA",
      releaseYear: 2008,
      genre: ["Action", "Crime", "Drama"],
      category: "Blockbuster",
      rating: 9.0,
      duration: "152 min",
      description: "When the Joker wreaks havoc and chaos on Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
      poster: "https://example.com/dark_knight.jpg"
    },
    {
      id: 6,
      title: "Pulp Fiction",
      actors: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
      director: "Quentin Tarantino",
      country: "USA",
      releaseYear: 1994,
      genre: ["Crime", "Drama"],
      category: "TrendingNow",
      rating: 8.9,
      duration: "154 min",
      description: "The lives of two mob hitmen, a boxer, a gangster, and his wife intertwine in four tales of violence and redemption.",
      poster: "https://example.com/pulp_fiction.jpg"
    },
    {
      id: 7,
      title: "The Matrix",
      actors: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
      director: "The Wachowskis",
      country: "USA",
      releaseYear: 1999,
      genre: ["Action", "Sci-Fi"],
      category: "Cult",
      rating: 8.7,
      duration: "136 min",
      description: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
      poster: "https://example.com/matrix.jpg"
    },
    {
      id: 8,
      title: "Forrest Gump",
      actors: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
      director: "Robert Zemeckis",
      country: "USA",
      releaseYear: 1994,
      genre: ["Drama", "Romance"],
      category: "NewThisWeek",
      rating: 8.8,
      duration: "142 min",
      description: "The presidencies of Kennedy and Johnson, Vietnam, Watergate, and other historical events unfold from the perspective of an Alabama man with a very low IQ.",
      poster: "https://example.com/forrest_gump.jpg"
    },
    {
      id: 9,
      title: "Schindler's List",
      actors: ["Liam Neeson", "Ralph Fiennes", "Ben Kingsley"],
      director: "Steven Spielberg",
      country: "USA",
      releaseYear: 1993,
      genre: ["Biography", "Drama", "History"],
      category: "Historical",
      rating: 9.0,
      duration: "195 min",
      description: "In German-occupied Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
      poster: "https://example.com/schindlers_list.jpg"
    },
    {
      id: 10,
      title: "Spirited Away",
      actors: ["Rumi Hiiragi", "Miyu Irino", "Mari Natsuki"],
      director: "Hayao Miyazaki",
      country: "Japan",
      releaseYear: 2001,
      genre: ["Animation", "Adventure", "Family"],
      category: "Anime",
      rating: 8.6,
      duration: "125 min",
      description: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, where humans are changed into beasts.",
      poster: "https://example.com/spirited_away.jpg"
    },
    {
      id: 11,
      title: "Fight Club",
      actors: ["Brad Pitt", "Edward Norton", "Meat Loaf"],
      director: "David Fincher",
      country: "USA",
      releaseYear: 1999,
      genre: ["Drama"],
      category: "Cult",
      rating: 8.8,
      duration: "139 min",
      description: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
      poster: "https://example.com/fight_club.jpg"
    },
    {
      id: 12,
      title: "Gladiator",
      actors: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen"],
      director: "Ridley Scott",
      country: "USA",
      releaseYear: 2000,
      genre: ["Action", "Adventure", "Drama"],
      category: "Epic",
      rating: 8.5,
      duration: "155 min",
      description: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
      poster: "https://example.com/gladiator.jpg"
    },
    {
      id: 13,
      title: "The Lord of the Rings: The Fellowship of the Ring",
      actors: ["Elijah Wood", "Ian McKellen", "Orlando Bloom"],
      director: "Peter Jackson",
      country: "New Zealand",
      releaseYear: 2001,
      genre: ["Adventure", "Drama", "Fantasy"],
      category: "Epic",
      rating: 8.8,
      duration: "178 min",
      description: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
      poster: "https://example.com/lotr_fellowship.jpg"
    },
    {
      id: 14,
      title: "The Social Network",
      actors: ["Jesse Eisenberg", "Andrew Garfield", "Justin Timberlake"],
      director: "David Fincher",
      country: "USA",
      releaseYear: 2010,
      genre: ["Biography", "Drama"],
      category: "Drama",
      rating: 7.8,
      duration: "120 min",
      description: "The story of the founders of Facebook and the resulting legal battles surrounding the company's rise to success.",
      poster: "https://example.com/social_network.jpg"
    },
    {
      id: 15,
      title: "Joker",
      actors: ["Joaquin Phoenix", "Robert De Niro", "Zazie Beetz"],
      director: "Todd Phillips",
      country: "USA",
      releaseYear: 2019,
      genre: ["Crime", "Drama", "Thriller"],
      category: "Blockbuster",
      rating: 8.4,
      duration: "122 min",
      description: "In Gotham City, a mentally troubled comedian embarks on a downward spiral of",
    },
        {
          id: 16,
          title: "Tomiris",
          actors: ["Almira Tursyn", "Adil Akhmetov", "Aizhan Lighg"],
          director: "Akan Satayev",
          country: "Kazakhstan",
          releaseYear: 2019,
          genre: ["Action", "Drama", "History"],
          category: "Historical",
          rating: 6.9,
          duration: "156 min",
          description: "The life and story of the great queen Tomiris, who united the Saka tribes and led them in defense of their freedom against the Persian Empire.",
          poster: "https://example.com/tomiris.jpg"
        },
        {
          id: 17,
          title: "The Road to Mother (Анаға апарар жол)",
          actors: ["Adil Akhmetov", "Berik Aitzhanov", "Altynai Nogerbek"],
          director: "Akan Satayev",
          country: "Kazakhstan",
          releaseYear: 2016,
          genre: ["Drama", "War"],
          category: "Drama",
          rating: 7.8,
          duration: "130 min",
          description: "A historical drama telling the story of a young man’s journey across decades to reunite with his mother, set against the backdrop of WWII and the Soviet era.",
          poster: "https://example.com/road_to_mother.jpg"
        },
        {
          id: 18,
          title: "Tulpan",
          actors: ["Askhat Kuchencherekov", "Samal Yeslyamova", "Ondasyn Besikbasov"],
          director: "Sergey Dvortsevoy",
          country: "Kazakhstan",
          releaseYear: 2008,
          genre: ["Drama", "Comedy"],
          category: "Indie",
          rating: 7.0,
          duration: "100 min",
          description: "A young man returns home after serving in the Russian Navy and dreams of marrying a local girl named Tulpan, but faces numerous challenges in the remote Kazakh steppe.",
          poster: "https://example.com/tulpan.jpg"
        },
        {
          id: 19,
          title: "Myn Bala: Warriors of the Steppe",
          actors: ["Asylkhan Tolepov", "Ayan Utepbergen", "Aliya Telebarisova"],
          director: "Akan Satayev",
          country: "Kazakhstan",
          releaseYear: 2012,
          genre: ["Action", "Drama", "History"],
          category: "Historical",
          rating: 6.7,
          duration: "100 min",
          description: "A historical epic about a group of young warriors who rise up to defend their people against the Dzungar invaders in 18th century Kazakhstan.",
          poster: "https://example.com/myn_bala.jpg"
        },
        {
          id: 20,
          title: "The Gift to Stalin",
          actors: ["Nurzhuman Ikhtymbaev", "Dina Tukubayeva", "Vladimir Tolokonnikov"],
          director: "Rustem Abdrashev",
          country: "Kazakhstan",
          releaseYear: 2008,
          genre: ["Drama", "Historical"],
          category: "Drama",
          rating: 7.4,
          duration: "97 min",
          description: "A boy escapes Stalin’s purges and is taken in by a kind-hearted railway worker in the remote Kazakh steppe, forming an unlikely bond as they try to survive.",
          poster: "https://example.com/gift_to_stalin.jpg"
        }
      ];
      